# Generated by Django 5.0.6 on 2024-08-06 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_program', models.CharField(max_length=300)),
                ('organisation', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='graduation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=300)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('degree', models.CharField(max_length=300)),
                ('stream', models.CharField(max_length=200)),
                ('performance_type', models.CharField(choices=[('percentage', 'Percentage'), ('cgpa10', 'CGPA 10'), ('cgpa9', 'CGPA 9'), ('cgpa8', 'CGPA 8'), ('cgpa7', 'CGPA 7'), ('cgpa6', 'CGPA 6'), ('cgpa5', 'CGPA 5'), ('cgpa4', 'CGPA 4'), ('cgpa3', 'CGPA 3'), ('cgpa2', 'CGPA 2'), ('cgpa1', 'CGPA 1')], max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=220)),
                ('profile', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=220)),
                ('profile', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.TextField()),
                ('github', models.TextField()),
                ('portfolio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Secondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=300)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('board', models.CharField(blank=True, choices=[('cbse', 'Central Board of Secondary Education (CBSE)'), ('icse', 'Council for the Indian School Certificate Examinations (CISCE/ICSE)'), ('nios', 'National Institute of Open Schooling (NIOS)'), ('ib', 'International Baccalaureate (IB)'), ('cambridge', 'Cambridge International Examinations (CIE)'), ('state-board', 'State Boards'), ('up-board', 'Uttar Pradesh Board of High School and Intermediate Education'), ('maharashtra-board', 'Maharashtra State Board of Secondary and Higher Secondary Education'), ('tamilnadu-board', 'Tamil Nadu State Board'), ('westbengal-board', 'West Bengal Board of Secondary Education'), ('karnataka-board', 'Karnataka Secondary Education Examination Board'), ('andhra-board', 'Andhra Pradesh Board of Secondary Education'), ('gujarat-board', 'Gujarat Secondary and Higher Secondary Education Board'), ('kerala-board', 'Kerala Board of Higher Secondary Education'), ('rajasthan-board', 'Board of Secondary Education Rajasthan'), ('punjab-board', 'Punjab School Education Board'), ('haryana-board', 'Board of School Education Haryana'), ('madhya-pradesh-board', 'Madhya Pradesh Board of Secondary Education'), ('bihar-board', 'Bihar School Examination Board'), ('chhattisgarh-board', 'Chhattisgarh Board of Secondary Education'), ('jharkhand-board', 'Jharkhand Academic Council'), ('assam-board', 'Board of Secondary Education Assam'), ('odisha-board', 'Board of Secondary Education Odisha')], max_length=255)),
                ('performance_type', models.CharField(choices=[('percentage', 'Percentage'), ('cgpa10', 'CGPA 10'), ('cgpa9', 'CGPA 9'), ('cgpa8', 'CGPA 8'), ('cgpa7', 'CGPA 7'), ('cgpa6', 'CGPA 6'), ('cgpa5', 'CGPA 5'), ('cgpa4', 'CGPA 4'), ('cgpa3', 'CGPA 3'), ('cgpa2', 'CGPA 2'), ('cgpa1', 'CGPA 1')], max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SeniorSecondary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=300)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('board', models.CharField(blank=True, choices=[('cbse', 'Central Board of Secondary Education (CBSE)'), ('icse', 'Council for the Indian School Certificate Examinations (CISCE/ICSE)'), ('nios', 'National Institute of Open Schooling (NIOS)'), ('ib', 'International Baccalaureate (IB)'), ('cambridge', 'Cambridge International Examinations (CIE)'), ('state-board', 'State Boards'), ('up-board', 'Uttar Pradesh Board of High School and Intermediate Education'), ('maharashtra-board', 'Maharashtra State Board of Secondary and Higher Secondary Education'), ('tamilnadu-board', 'Tamil Nadu State Board'), ('westbengal-board', 'West Bengal Board of Secondary Education'), ('karnataka-board', 'Karnataka Secondary Education Examination Board'), ('andhra-board', 'Andhra Pradesh Board of Secondary Education'), ('gujarat-board', 'Gujarat Secondary and Higher Secondary Education Board'), ('kerala-board', 'Kerala Board of Higher Secondary Education'), ('rajasthan-board', 'Board of Secondary Education Rajasthan'), ('punjab-board', 'Punjab School Education Board'), ('haryana-board', 'Board of School Education Haryana'), ('madhya-pradesh-board', 'Madhya Pradesh Board of Secondary Education'), ('bihar-board', 'Bihar School Examination Board'), ('chhattisgarh-board', 'Chhattisgarh Board of Secondary Education'), ('jharkhand-board', 'Jharkhand Academic Council'), ('assam-board', 'Board of Secondary Education Assam'), ('odisha-board', 'Board of Secondary Education Odisha')], max_length=255)),
                ('stream', models.CharField(max_length=200)),
                ('performance_type', models.CharField(choices=[('percentage', 'Percentage'), ('cgpa10', 'CGPA 10'), ('cgpa9', 'CGPA 9'), ('cgpa8', 'CGPA 8'), ('cgpa7', 'CGPA 7'), ('cgpa6', 'CGPA 6'), ('cgpa5', 'CGPA 5'), ('cgpa4', 'CGPA 4'), ('cgpa3', 'CGPA 3'), ('cgpa2', 'CGPA 2'), ('cgpa1', 'CGPA 1')], max_length=50)),
                ('score', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
