# Generated by Django 4.2.13 on 2024-08-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.URLField(),
        ),
    ]
