# Generated by Django 4.2.13 on 2024-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_portfolio_github_alter_portfolio_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
