# Generated by Django 4.2.13 on 2024-08-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_portfolio_github_alter_portfolio_linkedin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='seniorsecondary',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
