# Generated by Django 4.2.13 on 2024-08-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_graduation_score_alter_secondary_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduation',
            name='performance_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='secondary',
            name='performance_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA ')], max_length=50),
        ),
        migrations.AlterField(
            model_name='seniorsecondary',
            name='performance_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('cgpa', 'CGPA ')], max_length=50),
        ),
    ]
