# Generated by Django 4.2.13 on 2024-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_graduation_performance_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
